CREATE TABLE IF NOT EXISTS nodes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    properties JSONB NOT NULL DEFAULT '{}'::JSONB
);


CREATE INDEX IF NOT EXISTS node_property_idx ON nodes USING GIN(properties jsonb_path_ops);


CREATE TABLE IF NOT EXISTS node_labels (
    name VARCHAR(255) NOT NULL,
    node_id INTEGER NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
    UNIQUE(node_id, name)
);


CREATE TABLE IF NOT EXISTS edges (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id INTEGER NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
    target_id INTEGER NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
    properties JSONB NOT NULL DEFAULT '{}'::JSONB
);


CREATE INDEX IF NOT EXISTS edge_property_idx ON edges USING GIN(properties jsonb_path_ops);
CREATE INDEX IF NOT EXISTS edge_outgoing_idx ON edges(source_id, target_id);
CREATE INDEX IF NOT EXISTS edge_incoming_idx ON edges(target_id, source_id);


CREATE TABLE IF NOT EXISTS edge_labels (
    name VARCHAR(255) NOT NULL,
    edge_id INTEGER NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
    UNIQUE(edge_id, name)
);
